apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-paiarch-notebook 
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: notebook 
